# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Sigsh\Documents\testPyQt5\HelloPyQt\DeleteNoteDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DeleteNote(object):
    def setupUi(self, DeleteNote):
        DeleteNote.setObjectName("DeleteNote")
        DeleteNote.resize(300, 200)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DeleteNote.sizePolicy().hasHeightForWidth())
        DeleteNote.setSizePolicy(sizePolicy)
        DeleteNote.setMinimumSize(QtCore.QSize(300, 200))
        DeleteNote.setMaximumSize(QtCore.QSize(300, 200))
        font = QtGui.QFont()
        font.setPointSize(7)
        DeleteNote.setFont(font)
        DeleteNote.setSizeGripEnabled(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(DeleteNote)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(DeleteNote)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(37, 20, 191, 41))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.checkBox = QtWidgets.QCheckBox(self.frame)
        self.checkBox.setGeometry(QtCore.QRect(40, 60, 151, 51))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(11)
        self.checkBox.setFont(font)
        self.checkBox.setStyleSheet("")
        self.checkBox.setObjectName("checkBox")
        self.pushButton_yes = QtWidgets.QPushButton(self.frame)
        self.pushButton_yes.setGeometry(QtCore.QRect(30, 130, 101, 41))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_yes.setFont(font)
        self.pushButton_yes.setStyleSheet("QPushButton{\n"
"border:none;\n"
"background-color:rgb(67, 133, 200);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(17, 133, 195);\n"
"}")
        self.pushButton_yes.setObjectName("pushButton_yes")
        self.pushButton_no = QtWidgets.QPushButton(self.frame)
        self.pushButton_no.setGeometry(QtCore.QRect(150, 130, 101, 41))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_no.setFont(font)
        self.pushButton_no.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    background-color: rgb(229, 229, 229);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: lightgray;\n"
"}")
        self.pushButton_no.setObjectName("pushButton_no")
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(DeleteNote)
        QtCore.QMetaObject.connectSlotsByName(DeleteNote)

    def retranslateUi(self, DeleteNote):
        _translate = QtCore.QCoreApplication.translate
        DeleteNote.setWindowTitle(_translate("DeleteNote", "Dialog"))
        self.label.setText(_translate("DeleteNote", "是否要删除此笔记？"))
        self.checkBox.setText(_translate("DeleteNote", "不再询问"))
        self.pushButton_yes.setText(_translate("DeleteNote", "删除"))
        self.pushButton_no.setText(_translate("DeleteNote", "保留"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DeleteNote = QtWidgets.QDialog()
    ui = Ui_DeleteNote()
    ui.setupUi(DeleteNote)
    DeleteNote.show()
    sys.exit(app.exec_())
