# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Sigsh\Documents\testPyQt5\HelloPyQt\myNoteMenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NoteMenu(object):
    def setupUi(self, NoteMenu):
        NoteMenu.setObjectName("NoteMenu")
        NoteMenu.resize(400, 196)
        self.verticalLayout = QtWidgets.QVBoxLayout(NoteMenu)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_outer = QtWidgets.QFrame(NoteMenu)
        self.frame_outer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_outer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_outer.setObjectName("frame_outer")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_outer)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.frame_outer)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton_1 = QtWidgets.QRadioButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_1.sizePolicy().hasHeightForWidth())
        self.radioButton_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Candara Light")
        font.setPointSize(16)
        self.radioButton_1.setFont(font)
        self.radioButton_1.setStyleSheet("QRadioButton{\n"
"background-color: rgb(255, 230, 110);\n"
"}\n"
"QRadioButton::indicator{\n"
"width: 0px;\n"
"hight: 0px\n"
"}")
        self.radioButton_1.setChecked(True)
        self.radioButton_1.setObjectName("radioButton_1")
        self.horizontalLayout.addWidget(self.radioButton_1)
        self.radioButton_2 = QtWidgets.QRadioButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_2.sizePolicy().hasHeightForWidth())
        self.radioButton_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Candara Light")
        font.setPointSize(16)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setStyleSheet("QRadioButton{\n"
"background-color: rgb(161, 239, 155);\n"
"}\n"
"QRadioButton::indicator{\n"
"width: 0px;\n"
"hight: 0px\n"
"}")
        self.radioButton_2.setText("")
        self.radioButton_2.setChecked(False)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout.addWidget(self.radioButton_2)
        self.radioButton_3 = QtWidgets.QRadioButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_3.sizePolicy().hasHeightForWidth())
        self.radioButton_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Candara Light")
        font.setPointSize(16)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setStyleSheet("QRadioButton{\n"
"background-color: rgb(255, 175, 223);\n"
"}\n"
"QRadioButton::indicator{\n"
"width: 0px;\n"
"hight: 0px\n"
"}")
        self.radioButton_3.setText("")
        self.radioButton_3.setChecked(False)
        self.radioButton_3.setObjectName("radioButton_3")
        self.horizontalLayout.addWidget(self.radioButton_3)
        self.radioButton_4 = QtWidgets.QRadioButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_4.sizePolicy().hasHeightForWidth())
        self.radioButton_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Candara Light")
        font.setPointSize(16)
        self.radioButton_4.setFont(font)
        self.radioButton_4.setStyleSheet("QRadioButton{\n"
"background-color: rgb(215, 175, 255);\n"
"}\n"
"QRadioButton::indicator{\n"
"width: 0px;\n"
"hight: 0px\n"
"}")
        self.radioButton_4.setText("")
        self.radioButton_4.setChecked(False)
        self.radioButton_4.setObjectName("radioButton_4")
        self.horizontalLayout.addWidget(self.radioButton_4)
        self.radioButton_5 = QtWidgets.QRadioButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_5.sizePolicy().hasHeightForWidth())
        self.radioButton_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Candara Light")
        font.setPointSize(16)
        self.radioButton_5.setFont(font)
        self.radioButton_5.setStyleSheet("QRadioButton{\n"
"background-color: rgb(158, 223, 255);\n"
"}\n"
"QRadioButton::indicator{\n"
"width: 0px;\n"
"hight: 0px\n"
"}")
        self.radioButton_5.setText("")
        self.radioButton_5.setChecked(False)
        self.radioButton_5.setObjectName("radioButton_5")
        self.horizontalLayout.addWidget(self.radioButton_5)
        self.radioButton_6 = QtWidgets.QRadioButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_6.sizePolicy().hasHeightForWidth())
        self.radioButton_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Candara Light")
        font.setPointSize(16)
        self.radioButton_6.setFont(font)
        self.radioButton_6.setStyleSheet("QRadioButton{\n"
"background-color: rgb(224, 224, 224);\n"
"}\n"
"QRadioButton::indicator{\n"
"width: 0px;\n"
"hight: 0px\n"
"}")
        self.radioButton_6.setText("")
        self.radioButton_6.setChecked(False)
        self.radioButton_6.setObjectName("radioButton_6")
        self.horizontalLayout.addWidget(self.radioButton_6)
        self.radioButton_7 = QtWidgets.QRadioButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_7.sizePolicy().hasHeightForWidth())
        self.radioButton_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Candara Light")
        font.setPointSize(16)
        self.radioButton_7.setFont(font)
        self.radioButton_7.setStyleSheet("QRadioButton{\n"
"background-color: rgb(118, 118, 118);\n"
"}\n"
"QRadioButton::indicator{\n"
"width: 0px;\n"
"hight: 0px\n"
"}")
        self.radioButton_7.setText("")
        self.radioButton_7.setChecked(False)
        self.radioButton_7.setObjectName("radioButton_7")
        self.horizontalLayout.addWidget(self.radioButton_7)
        self.verticalLayout_2.addWidget(self.frame)
        self.pushButton = QtWidgets.QPushButton(self.frame_outer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"border:none;\n"
"background-color: white;\n"
"text-align:left;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(237, 237, 237);\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resources/align-left.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.pushButton_delete = QtWidgets.QPushButton(self.frame_outer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_delete.sizePolicy().hasHeightForWidth())
        self.pushButton_delete.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_delete.setFont(font)
        self.pushButton_delete.setStyleSheet("QPushButton{\n"
"border:none;\n"
"color: rgb(255, 0, 0);\n"
"background-color:white;\n"
"text-align:left;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(237, 237, 237);\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/resources/trash-2_red.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_delete.setIcon(icon1)
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.verticalLayout_2.addWidget(self.pushButton_delete)
        self.verticalLayout.addWidget(self.frame_outer)

        self.retranslateUi(NoteMenu)
        QtCore.QMetaObject.connectSlotsByName(NoteMenu)

    def retranslateUi(self, NoteMenu):
        _translate = QtCore.QCoreApplication.translate
        NoteMenu.setWindowTitle(_translate("NoteMenu", "Form"))
        self.radioButton_1.setText(_translate("NoteMenu", "√"))
        self.pushButton.setText(_translate("NoteMenu", "便笺列表"))
        self.pushButton_delete.setText(_translate("NoteMenu", "删除笔记"))
import images_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NoteMenu = QtWidgets.QWidget()
    ui = Ui_NoteMenu()
    ui.setupUi(NoteMenu)
    NoteMenu.show()
    sys.exit(app.exec_())
